config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "notices#home"
  get "result", to: "notices#result"
  resources :notices
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  def home
    
  end

  def result
    count = Notice.count
    @notice = Notice.find(rand(count) + 1)
  end

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notice_params
      params.require(:notice).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="UTF-8"
    meta http-equiv="X-UA-Compatibile" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    title サッパラス占い

    meta name="description" content="占い師による的中率 97.2% の占いです。"

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/united/bootstrap.min.css" rel="stylesheet" integrity="sha384-0UBL8wxZ28kqJ8w8N8RUV0odBG5w8D/Y+rb+o7hr2F3dS9twlAE8S7VUtVSRe5cc" crossorigin="anonymous"
    link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous"

    <!-- iconj.com animated favicon code -->
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="/favicon.ico" type="image/gif" />
    <!-- end of iconj.com animated favicon code -->

  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed data-toggle="collapse" data-target="#navbarMenu"
            span.sr-only メニュー
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" サッパラス占い
          p.navbar-text ※的中率 97.2%
        .collapse.navbar-collapse id="navbarMenu"
          ul.nav.navbar-nav.navbar-right
            li.dropdown
              a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                | リンク
                span.caret
              ul.dropdown-menu role="menu"
                li
                  a href="https://www.zappallas.com/" target="_blank" ザッパラス

    /== render "layouts/flash"

    .container.page-header
      == yield

    footer
     .container
        p.text-center.text-muted &copy; 2020 サッパラス All Rights Reserved.

    script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"

app/views/notices/_form.html.erb
<%= form_with(model: notice, local: true) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/home.html.slim
row
  br
  br
  .panel.panel-default
    .panel-body
      form action="result" method="get"
        div.form-group
          label 生年月日
          input.form-control type="date" placeholder="生年月日を入れてください。"
          small.form-text.text-muted あなたの今日の運勢を占います。
        button.btn.btn-primary type="submit" 占う！

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.title %></td>
        <td><%= notice.content %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/result.html.slim
row
  br
  br
  .panel.panel-default
    .panel-heading
      = @notice.title
    .panel-body
      = @notice.content

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notice.content %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>